[project]
name            = "WebScanner-X"
version         = "1.5.5"
description     = "Un Scanner de sites web ecrit en Python - <CLI Tool>"
readme          = "README.md"
authors         = [{name = "Cyber-Tchak"}]
license         = "MIT"
requires-python = ">=3.8"
dependencies    = [
    "requests",
    "colorama",
]

[project.scripts]
WebScan = "WebScanner:WebScanner_run"


[build-system]
requires      = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
package-dir = {"WebScanner" = "."}
packages    = [
    "WebScanner",
    "WebScanner.core",
    "WebScanner.core.modules",
    "WebScanner.utils",
    "WebScanner.configs"
]

